name: Release
permissions:
  contents: write

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create ZIP file
      run: |
        zip -r project.zip src include
