name: Release
permissions:
  contents: write

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create ZIP file
      run: |
        zip -r project.zip src include CMakeLists.txt

    - name: Add ZIP file to release
      uses: svenstaro/upload-release-action@v2
      with: 
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: project.zip
        tag: ${{ github.ref }}
